using FFRK_LabMem.Data;
using System;
using System.Linq;
using System.Collections.Generic;
using FFRK_Machines.Services.Notifications;
using System.ComponentModel;
using System.Windows.Forms;

namespace FFRK_LabMem.Config.UI
{
    class Lookups
    {
        // List of painting names in Japanese and their translations
        public static readonly Dictionary<String, String> PaintingStrings = new Dictionary<String, String>()
        {
            { "戦いの絵画", "Combatant Painting" },
            { "探索の絵画", "Exploration Painting" },
            { "癒しの絵画", "Restoration Painting" },
            { "躍進の絵画", "Onslaught Painting" },
            { "宝物庫の絵画", "Treasure Painting" },
            { "転送の絵画", "Portal Painting" },
            { "堅牢の絵画", "Master Painting" }
        };

        // List of enemy names in Japanese and their translations
        public static readonly Dictionary<String, String> Enemies = new Dictionary<String, String>()
        {
            { "【迷宮】アダマンケリス", "Adamanchelid" },
            { "【迷宮】アダマンタイマイ", "Adamantoise" },
            { "【迷宮】アデル", "Adel" },
            { "【迷宮】アドラメレク", "Adrammelech" },
            { "【迷宮】アーリマン＆ケルベロス", "Ahriman & Cerberus" },
            { "【迷宮】アレキサンダー", "Alexander" },
            { "【迷宮】アンジールペナンス",  "Angeal Penance" },
            { "【迷宮】アルケニー", "Arachne" },
            { "【迷宮】アトモス", "Atomos" },
            { "【迷宮】バハムート", "Bahamut" },
            { "【迷宮】バンダースナッチ", "Bandersnatch" },
            { "【迷宮】バラライ", "Baralai" },
            { "【迷宮】バルバリシア", "Barbariccia" },
            { "【迷宮】バルク＆ナイト＆弓使い＆黒魔道士", "Barich, Knight, Archer & Black Mage" },
            { "【迷宮】ベヒーモス", "Behemoth" },
            { "【迷宮】ビッグホーン", "Big Horn" },
            { "【迷宮】ブラックプリン", "Black Flan" },
            { "【迷宮】黒のワルツ2号", "Black Waltz 2" },
            { "【迷宮】ビブロス", "Byblos" },
            { "【迷宮】ブリュンヒルデ", "Brynhildr" },
            { "【迷宮】カーバンクル", "Carbuncle" },
            { "【迷宮】ケルべロス", "Cerberus" },
            { "【迷宮】カオス", "Chaos" },
            { "【迷宮】ヘレティック・イフリート", "Dark Ifrit" },
            { "【迷宮】ヘレティック・ヴァルファーレ", "Dark Valefor" },
            { "【迷宮】デスクロー", "Deathclaw" },
            { "【迷宮】デスマシーン", "Death Machine" },
            { "【迷宮】ディアボロス", "Diablos" },
            { "【迷宮】バクライリュウ", "Diepvern" },
            { "【迷宮】ドレッドノート", "Dreadnought" },
            { "【迷宮】ダイスダーグ", "Dycedarg" },
            { "【迷宮】エキドナ", "Echidna" },
            { "【迷宮】エンキドゥ", "Enkidu" },
            { "【迷宮】エクスデス", "Exdeath" },
            { "【迷宮】エクスペリメント", "Experiment" },
            { "【迷宮】マルドゥーク", "Faeryl" },
            { "【迷宮】ヴォルマルフ＆ローファル＆クレティアン", "Folmarv, Loffrey, & Cletienne" },
            { "【迷宮】ジェネラル", "General" },
            { "【迷宮】ギザマルーク", "Gizamaluke" },
            { "【迷宮】グリーンドラゴン", "Green Dragon" },
            { "【迷宮】剣聖ギルガメッシュ", "Gilgamesh" },
            { "【迷宮】ゴールドル", "Goldor" },
            { "【迷宮】ガードスコーピオン", "Guard Scorpion" },
            { "【迷宮】ハシュマリム", "Hashmal" },
            { "【迷宮】ヘルハウス", "Hell House" },
            { "【迷宮】鉄巨人", "Iron Giant" },
            { "【迷宮】キングベヒーモス", "King Behemoth" },
            { "【迷宮】クーンキリフ", "Kukulkan" },
            { "【迷宮】ラニ＆焔色の髪の男", "Lani & Scarlet Hair" },
            { "【迷宮】リバイアサン", "Leviathan" },
            { "【迷宮】リッチ&【迷宮】バンパイア", "Lich & Vampire" },
            { "【迷宮】ルナザウルス", "Lunasaur" },
            { "【迷宮】マジックポット", "Magic Pot" },
            { "【迷宮】魔導アーマー", "Magitek Armor" },
            { "【迷宮】マリリス", "Marilith" },
            { "【迷宮】メルティジェミニ", "Meltigemini" },
            { "【迷宮】モーターボール", "Motor Ball" },
            { "【迷宮】ミスリルゴーレム", "Mythril Golem" },
            { "【迷宮】ナーガ", "Naga" },
            { "【迷宮】ネオチュー", "Neochu" },
            { "【迷宮】ネオガルラ", "Neo Garula" },
            { "【迷宮】ニーズヘッグ", "Nidhogg" },
            { "【迷宮】ニンジャ", "Ninja" },
            { "【迷宮】にんじゃ＆ようじんぼう", "Ninja & Yojimbo" },
            { "【迷宮】神竜", "Nova Dragon" },
            { "【迷宮】オーディン", "Odin" },
            { "【迷宮】タイダリアサン", "Ogopogo" },
            { "【迷宮】パンデモニウム", "Pandaemonium" },
            { "【迷宮】プラントブレイン", "Plant Brain" },
            { "【迷宮】ケツァルコアトル", "Quetzalcoatl" },
            { "【迷宮】ラムザ", "Ramza" },
            { "【迷宮】レイヴス", "Ravus" },
            { "【迷宮】赤竜", "Red Dragon" },
            { "【迷宮】ウルフラマイター＆【迷宮】カトブレパス", "Red Giant & Catoblepas" },
            { "【迷宮】ラウンドウォーム", "Roundworm" },
            { "【迷宮】完熟大王", "Royal Ripeness" },
            { "【迷宮】ルーファウス", "Rufus" },
            { "【迷宮】セクレト&【迷宮】ミノタウロス", "Sacred & Minotaur" },
            { "【迷宮】銀竜", "Silver Dragon" },
            { "【迷宮】シャーリート", "Slyt" },
            { "【迷宮】ソル カノン＆ランチャー", "Soul Cannon" },
            { "【迷宮】ストームドラゴン", "Storm Dragon" },
            { "【迷宮】ティターン", "Titan" },
            { "【迷宮】ドルメン＆アリニュメン", "Trauma & Droma" },
            { "【迷宮】ツインタニア", "Twintania" },
            { "【迷宮】タイラント", "Tyrant" },
            { "【迷宮】アルテマウェポン", "Ultima Weapon" },
            { "【迷宮】ヴァジュラ", "Vajra" },
            { "【迷宮】ウェンディゴ", "Wendigo" },
            { "【迷宮】ザグナル", "Zaghnol" },
            { "【迷宮】ゼムス", "Zemus" },
            { "【迷宮】ゾンビボーゲン", "Zombie Borghen" }
        };

        // Lists enemies who have multiple copies in battles
        public static readonly Dictionary<String, String> EnemyNumber = new Dictionary<String, String>()
        {
            { "Big Horn", "×4" },
            { "Black Flan", "×2" },
            { "Dreadnought", "×2" },
            { "Green Dragon", "×2" },
            { "Lunasaur", "×2" },
            { "Magitek Armor", "×2" },
            { "Neochu", "×2" },
            { "Neo Garula", "×2" },
        };

        public static readonly Dictionary<String, String> Items = new Dictionary<string, string>()
        {
            { "アダマンタイト【極大】", "Major Adamantite" },
            { "ギル", "Gil" },
            { "アルカナ【大】", "Greater Arcana" },
            { "グロウエッグ(極大)", "Major Growth Egg" },
            { "レテのしずく", "Lethe Tear" },
            { "魔法の鍵", "Magic Key" },
            { "記憶のしおり", "Record Marker" },
            { "七色の結晶", "Rainbow Shard" },
            { "叡智のロゼッタ石", "Rosette Stone of Wisdom" },
            { "ヒヒイロカネ【極大】", "Giant Scaletite" },
            { "テレポストーン", "Teleport Stone" },
            { "秘宝の地図", "Treasure Map" },
        };

        public static readonly Dictionary<String, String> Characters = new Dictionary<string, string>()
        {
            { "光の戦士", "Warrior of Light" },
            { "エコー", "Echo" },
            { "セーラ", "Sarah" },
            { "ウォル", "Wol" },
            { "ガーランド", "Garland" },
            { "スーパーモンク", "Master" },
            { "マトーヤ", "Matoya" },
            { "メイア", "Meia" },
            { "シーフ(I)", "Thief (I)" },
            { "ヨーゼフ", "Josef" },
            { "ゴードン", "Gordon" },
            { "フリオニール", "Firion" },
            { "リチャード", "Ricard" },
            { "レオンハルト", "Leon" },
            { "マリア", "Maria" },
            { "レイラ", "Leila" },
            { "ミンウ", "Minwu" },
            { "ガイ", "Guy" },
            { "皇帝", "Emperor" },
            { "スコット", "Scott" },
            { "ヒルダ", "Hilda" },
            { "ルーネス", "Luneth" },
            { "アルクゥ", "Arc" },
            { "レフィア", "Refia" },
            { "イングズ", "Ingus" },
            { "デッシュ", "Desch" },
            { "オニオンナイト", "Onion Knight" },
            { "暗闇の雲", "Cloud of Darkness" },
            { "エリア", "Aria" },
            { "カイン", "Kain" },
            { "セシル(暗黒騎士)", "Cecil (Dark Knight)" },
            { "リディア", "Rydia" },
            { "セシル(パラディン)", "Cecil (Paladin)" },
            { "テラ", "Tellah" },
            { "ゴルベーザ", "Golbez" },
            { "ギルバート", "Edward" },
            { "フースーヤ", "Fusoya" },
            { "ローザ", "Rosa" },
            { "エッジ", "Edge" },
            { "パロム", "Palom" },
            { "ポロム", "Porom" },
            { "ヤン", "Yang" },
            { "シド(IV)", "Cid (IV)" },
            { "セオドア", "Ceodore" },
            { "ルビカンテ", "Rubicante" },
            { "アーシュラ", "Ursula" },
            { "バルバリシア", "Barbariccia" },
            { "レナ", "Lenna" },
            { "ガラフ", "Galuf" },
            { "ギルガメッシュ", "Gilgamesh" },
            { "バッツ", "Bartz" },
            { "ファリス", "Faris" },
            { "クルル", "Krile" },
            { "エクスデス", "Exdeath" },
            { "ドルガン", "Dorgann" },
            { "ものまねしゴゴ", "Gogo (V)" },
            { "ケルガー", "Kelger" },
            { "ゼザ", "Xezat" },
            { "ティナ", "Terra" },
            { "ストラゴス", "Strago" },
            { "セリス", "Celes" },
            { "セッツァー", "Setzer" },
            { "ロック", "Locke" },
            { "モグ", "Mog" },
            { "エドガー", "Edgar" },
            { "マッシュ", "Sabin" },
            { "シャドウ", "Shadow" },
            { "カイエン", "Cyan" },
            { "ガウ", "Gau" },
            { "ケフカ", "Kefka" },
            { "リルム", "Relm" },
            { "レオ将軍", "Leo" },
            { "ゴゴ", "Gogo (VI)" },
            { "ウーマロ", "Umaro" },
            { "オルトロス", "Ultros" },
            { "クラウド", "Cloud" },
            { "エアリス", "Aerith" },
            { "ティファ", "Tifa" },
            { "セフィロス", "Sephiroth" },
            { "レッドXIII", "Red XIII" },
            { "ザックス", "Zack" },
            { "バレット", "Barret" },
            { "シド(VII)", "Cid (VII)" },
            { "レノ", "Reno" },
            { "ユフィ", "Yuffie" },
            { "ヴィンセント", "Vincent" },
            { "ケット・シー", "Cait Sith" },
            { "アンジール", "Angeal" },
            { "ルーファウス", "Rufus" },
            { "シェルク", "Shelke" },
            { "ルード", "Rude" },
            { "イリーナ", "Elena" },
            { "ジェネシス", "Genesis" },
            { "リノア", "Rinoa" },
            { "アーヴァイン", "Irvine" },
            { "スコール", "Squall" },
            { "セルフィ", "Selphie" },
            { "キスティス", "Quistis" },
            { "ゼル", "Zell" },
            { "サイファー", "Seifer" },
            { "ラグナ", "Laguna" },
            { "イデア", "Edea" },
            { "雷神", "Raijin" },
            { "風神", "Fujin" },
            { "キロス", "Kiros" },
            { "ウォード", "Ward" },
            { "アルティミシア", "Ultimecia" },
            { "ビビ", "Vivi" },
            { "ガーネット", "Garnet" },
            { "スタイナー", "Steiner" },
            { "エーコ", "Eiko" },
            { "サラマンダー", "Amarant" },
            { "ジタン", "Zidane" },
            { "クイナ", "Quina" },
            { "ベアトリクス", "Beatrix" },
            { "フライヤ", "Freya" },
            { "クジャ", "Kuja" },
            { "マーカス", "Marcus" },
            { "ティーダ", "Tidus" },
            { "ワッカ", "Wakka" },
            { "キマリ", "Kimahri" },
            { "ユウナ", "Yuna" },
            { "アーロン", "Auron" },
            { "ルールー", "Lulu" },
            { "リュック", "Rikku" },
            { "ジェクト", "Jecht" },
            { "ブラスカ", "Braska" },
            { "パイン", "Paine" },
            { "シーモア", "Seymour" },
            { "シャントット", "Shantotto" },
            { "アヤメ", "Ayame" },
            { "クリルラ", "Curilla" },
            { "プリッシュ", "Prishe" },
            { "ライオン", "Lion" },
            { "アフマウ", "Aphmau" },
            { "ザイド", "Zeid" },
            { "リリゼット", "Lilisette" },
            { "ナジャ", "Naja" },
            { "アシェラ", "Arciela" },
            { "フラン", "Fran" },
            { "バルフレア", "Balthier" },
            { "ヴァン", "Vaan" },
            { "アーシェ", "Ashe" },
            { "パンネロ", "Penelo" },
            { "バッシュ", "Basch" },
            { "ガブラス", "Gabranth" },
            { "ラーサー", "Larsa" },
            { "ヴェイン", "Vayne" },
            { "レックス", "Reks" },
            { "スノウ", "Snow" },
            { "ヴァニラ", "Vanille" },
            { "ライトニング", "Lightning" },
            { "サッズ", "Sazh" },
            { "ホープ", "Hope" },
            { "ファング", "Fang" },
            { "セラ", "Serah" },
            { "レインズ", "Cid Raines" },
            { "ノエル", "Noel" },
            { "ナバート", "Nabaat" },
            { "ヤ・シュトラ", "Y'shtola" },
            { "サンクレッド", "Thancred" },
            { "イダ", "Yda" },
            { "パパリモ", "Papaylmo" },
            { "アルフィノ", "Alphinaud" },
            { "ミンフィリア", "Minfilia" },
            { "シド(XIV)", "Cid (XIV)" },
            { "イゼル", "Ysayle" },
            { "オルシュファン", "Haurchefant" },
            { "エスティニアン", "Estinien" },
            { "アリゼー", "Alisaie" },
            { "ノクティス", "Noctis" },
            { "グラディオラス", "Gladiolus" },
            { "イリス", "Iris" },
            { "プロンプト", "Prompto" },
            { "アラネア", "Aranea" },
            { "イグニス", "Ignis" },
            { "コル", "Cor" },
            { "ルナフレーナ", "Lunafreya" },
            { "アーデン", "Ardyn" },
            { "レイヴス", "Ravus" },
            { "クライヴ", "Clive" },
            { "ジル", "Jill" },
            { "ジョシュア", "Joshua" },
            { "シドルファス", "Cidolfus" },
            { "トルガル", "Torgal" },
            { "ラムザ", "Ramza" },
            { "アグリアス", "Agrias" },
            { "オヴェリア", "Ovelia" },
            { "ムスタディオ", "Mustadio" },
            { "ディリータ", "Delita" },
            { "オルランドゥ", "Orlandeau" },
            { "ガフガリオン", "Gaffgarion" },
            { "ラファ", "Rapha" },
            { "マラーク", "Marach" },
            { "メリアドール", "Meliadoul" },
            { "マーシュ", "Marche" },
            { "モンブラン", "Montblanc" },
            { "アルマ", "Alma" },
            { "オーラン", "Orran" },
            { "エース", "Ace" },
            { "デュース", "Deuce" },
            { "ナイン", "Nine" },
            { "マキナ", "Machina" },
            { "レム", "Rem" },
            { "クイーン", "Queen" },
            { "キング", "King" },
            { "シンク", "Cinque" },
            { "セブン", "Seven" },
            { "サイス", "Sice" },
            { "ジャック", "Jack" },
            { "エイト", "Eight" },
            { "ケイト", "Cater" },
            { "トレイ", "Trey" },
            { "クラサメ", "Kurasame" },
            { "レェン", "Reynn" },
            { "ラァン", "Lann" },
            { "トゥモロ", "Morrow" },
            { "エモ", "Aemo" },
            { "リーグ", "Wrieg" },
            { "タマ", "Tama" },
            { "エナ・クロ", "Enna Kros" },
            { "セラフィ", "Serafie" },
            { "レイン", "Rain" },
            { "フィーナ", "Fina" },
            { "デシ", "Tyro" },
            { "ウララ", "Elarra" },
            { "ビッグス", "Biggs" },
            { "ウェッジ", "Wedge" },
            { "Dr.モグ", "Dr. Mog" },
            { "シャドウスミス", "Shadowsmith" }
        };

        public static readonly Dictionary<String, String> MoteTypes = new Dictionary<String, String>()
        {
            { "技", "Dexterity" },
            { "心", "Spirit" },
            { "体", "Vitality" },
            { "知", "Wisdom" },
            { "勇", "Bravery" }
        };

        public static readonly Dictionary<String, String> AnimaTypes = new Dictionary<String, String>()
        {
            { "Lv1", "Lv1" },
            { "Lv2", "Lv2" },
            { "Lv3", "Lv3" },
            { "EX", "EX" }
        };

        public static readonly Dictionary<String, String> Rarities = new Dictionary<String, String>()
        {
            { "3)", "3★)" },
            { "4)", "4★)" },
            { "5)", "5★)" },
            { "6)", "6★)" },
            { "7)", "7★)" }
        };

        public static readonly Dictionary<String, String> Sizes = new Dictionary<String, String>()
        {
            { "【中】", "" },
            { "【大】", "Greater " },
            { "【極大】", "Major " }
        };

        // List of orb/crystal types in Japanese and their translations
        public static readonly Dictionary<String, String> OrbTypes = new Dictionary<String, String>()
        {
            { "炎", "Fire" },
            { "氷", "Ice" },
            { "雷", "Lightning" },
            { "水", "Water" },
            { "風", "Wind" },
            { "地", "Earth" },
            { "聖", "Holy" },
            { "闇", "Dark" },
            { "毒", "Poison" },
            { "無", "Non-Elemental" },
            { "力", "Power" },
            { "白", "White" },
            { "黒", "Black" },
            { "召喚", "Summoning" }
        };

        public static Dictionary<String, String> Paintings = new Dictionary<string, string>() {
            {"1.1", "Combatant Painting (Green)"},
            {"1.2", "Combatant Painting (Orange)"},
            {"1.3", "Combatant Painting (Red)"},
            {"2", "Master Painting"},
            {"3", "Treasure Painting"},
            {"4", "Exploration Painting"},
            {"5", "Onslaught Painting"},
            {"6", "Portal Painting"},
            {"7", "Restoration Painting"},
            {"R", "Radiant Painting"}
        };

        public static Dictionary<String, String> Treasures = new Dictionary<string, string>() {
            {"5", "Hero Motes/Equipment"},
            {"4", "Anima Lenses, Bookmark, 5★ Rat Tails, Map ×2, Teleport Stone"},
            {"3", "7★/6★ Motes, 4★ Rat Tails, Magic Key, Treasure Map, Lethe Potion"},
            {"2", "6★ Crystals, Rainbow Crystal, Rosetta Stone of Wisdom"},
            {"1", "5★ Orbs, 5★ Motes"}
        };

        public static BindingList<AdbHostItem> AdbHosts = new BindingList<AdbHostItem>() {
            new AdbHostItem { Name = "MuMu", Value = "127.0.0.1:7555"} ,
            new AdbHostItem { Name = "Nox", Value = "127.0.0.1:62001"} ,
            new AdbHostItem { Name = "Nox Alt 1", Value = "127.0.0.1:62025"} ,
            new AdbHostItem { Name = "Nox Alt 2", Value = "127.0.0.1:62026"} ,
            new AdbHostItem { Name = "Nox Alt 3", Value = "127.0.0.1:62027"} ,
            new AdbHostItem { Name = "MEmu", Value = "127.0.0.1:21503"} ,
            new AdbHostItem { Name = "MEmu Instance 2", Value = "127.0.0.1:21513"} ,
            new AdbHostItem { Name = "MEmu Instance 3", Value = "127.0.0.1:21523"} ,
            new AdbHostItem { Name = "Other", Value = "127.0.0.1:5555"}
        };

        public static Dictionary<String, String> Timings = new Dictionary<string, string>() {
            {"Pre-SelectPainting", "Delay before selecting a painting"},
            {"Inter-SelectPainting", "Delay between selecting a painting and confirming it"},
            {"Pre-SelectTreasure", "Delay before selecting the first treasure"},
            {"Pre-Door", "Delay before either opening or leaving a sealed door"},
            {"Pre-MoveOn", "Delay before moving on after most explore results"},
            {"Post-Battle","Delay before pressing skip after a battle ends" },
            {"Pre-RestartLab","Delay before starting a new lab run when degenerate mode is enabled" },
            {"Inter-RestartFFRK-Timeout","How long to wait when restarting FFRK before giving up" },
            {"Inter-RestartLab-Stamina","DEPRECATED: Use X-Stamina timings instead" },
        };

        public static Dictionary<String, String> Blocklist = new Dictionary<string, string>() {
            {"Alexander", "High resistance"},
            {"Atomos", "Slowga, High damage"},
            {"Diablos", "High damage"},
            {"Lani & Scarlet Hair", "Damage sponge"},
            {"Lunasaurs", "Reflect"},
            {"Octomammoth","Reflect" },
            {"Marilith", "High resistance, Blind" },
            {"Vajra", "High damage" }
        };

        public static Dictionary<String, String> Counters = new Dictionary<string, string>() {
            {"LabRunsCompleted", "Lab Runs Completed"},
            {"PaintingsSelected", "Paintings Selected"},
            {"BattlesWon", "Battles Won"},
            {"TreasuresOpened", "Treasures Opened"},
            {"RadiantPaintings", "Radiant Paintings Found"},
            {"MagicPots", "Magic Pots Found"},
            {"UsedTears", "Lethe Tears Used"},
            {"UsedKeys", "Magic Keys Used"},
            {"UsedTeleportStones", "Teleport Stones Used"},
            {"UsedStaminaPots", "Stamina Pots Used"},
            {"PulledInPortal", "Pulled Into Portals"},
            {"FFRKCrashes", "FFRK Crashed"},
            {"FFRKHangs", "FFRK Hangs"},
            {"FFRKRecoveries", "FFRK Recovered"},
            {"FFRKRestarts", "FFRK Restarted"},
            {"HeroEquipmentGot", "Hero Equipment Found"},
            {"EnemyIsUponYou", "The Enemy is Upon You!"},
            {"QuickExplores", "Quick Explores"},
        };

        public static AutoCompleteStringCollection EnemyAC = new AutoCompleteStringCollection();
        
        public static Dictionary<Counters.DropCategory, String> DropCategories = new Dictionary<Counters.DropCategory, string>() {
            {Data.Counters.DropCategory.EQUIPMENT, "Hero Equipment"},
            {Data.Counters.DropCategory.LABYRINTH_ITEM, "Labyrinth Items (Bookmarks, Keys...)"},
            {Data.Counters.DropCategory.COMMON, "Anima Lenses"},
            {Data.Counters.DropCategory.SPHERE_MATERIAL, "Motes"},
            {Data.Counters.DropCategory.ABILITY_MATERIAL, "Crystals/Orbs"},
            {Data.Counters.DropCategory.EQUIPMENT_SP_MATERIAL,"Upgrade Materials" },
            {Data.Counters.DropCategory.HISTORIA_CRYSTAL_ENHANCEMENT_MATERIAL, "Rat Tails" },
            {Data.Counters.DropCategory.GROW_EGG, "Growth Eggs" },
            {Data.Counters.DropCategory.BEAST_FOOD, "Arcana" },
            {Data.Counters.DropCategory.RECORD_MATERIA, "Record Materia" }
        };

        public static Dictionary<String, Counters.DropCategory> DropCategoriesInverse = DropCategories.ToDictionary((i) => i.Value, (i) => i.Key);
        

        public static Dictionary<Notifications.EventType, String> NotificationEvents = new Dictionary<Notifications.EventType, string>() {
            {Notifications.EventType.LAB_COMPLETED, "Lab Completed"},
            {Notifications.EventType.LAB_FAULT, "Lab Fault"},
        };

        public static Dictionary<String, Notifications.EventType> NotificationEventsInverse = NotificationEvents.ToDictionary((i) => i.Value, (i) => i.Key);

    }
}
